version: '3'

services:
  mellifera:
    image: python:3.11-buster
    restart: always
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ./docker-entrypoint.sh
    stdin_open: true
    tty: true
